version: '3'
services:
  jupyter:
    image: osuarez/lp-jupyter:v3.0
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/src
