version: '3'
volumes:
  prometheus_data:
  grafana_data:

services:
  model:
    image: osuarez/lp-service:latest
    build:
      context: ../service
      dockerfile: Dockerfile
    container_name: service
    restart: unless-stopped
    expose:
      - "8000"
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v2.20.0
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus # Get the config file
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=48h'
    restart: unless-stopped
    expose:
      - "9090"

  grafana:
    image: grafana/grafana:7.1.1
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD-admin}
      - GF_USERS_ALLOW_SIGN_UP=false

  caddy:
    image: stefanprodan/caddy
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./caddy:/etc/caddy
    environment:
      - ADMIN_USER=${ADMIN_USER-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD-admin}
    ports:
      - "3000:3000"
      - "9090:9090"
